export const skills = {
  languages: [
    { name: "TypeScript", level: 95 },
    { name: "JavaScript", level: 95 },
    { name: "Python", level: 90 },
    { name: "Go", level: 85 },
    { name: "Java", level: 80 },
  ],
  frontend: [
    { name: "React", level: 95 },
    { name: "Next.js", level: 90 },
    { name: "Tailwind CSS", level: 95 },
    { name: "shadcn/ui", level: 90 },
    { name: "Zustand", level: 85 },
    { name: "Redux", level: 85 },
  ],
  mobile: [
    { name: "React Native", level: 95 },
    { name: "Expo", level: 90 },
    { name: "TypeScript", level: 95 },
    { name: "React Navigation", level: 90 },
    { name: "Redux Toolkit", level: 85 },
    { name: "Firebase", level: 85 },
    { name: "iOS Development", level: 80 },
    { name: "Android Development", level: 80 },
  ],
  backend: [
    { name: "Node.js", level: 95 },
    { name: "Express", level: 90 },
    { name: "Django", level: 85 },
    { name: "REST APIs", level: 95 },
    { name: "GraphQL", level: 85 },
    { name: "PostgreSQL", level: 90 },
    { name: "MongoDB", level: 85 },
  ],
  devops: [
    { name: "Docker", level: 95 },
    { name: "Kubernetes", level: 90 },
    { name: "Helm", level: 85 },
    { name: "Terraform", level: 90 },
    { name: "AWS", level: 95 },
    { name: "GCP", level: 85 },
    { name: "Cloudflare", level: 80 },
    { name: "Linux", level: 95 },
  ],
  cicd: [
    { name: "GitHub Actions", level: 95 },
    { name: "Jenkins", level: 85 },
    { name: "GitLab CI", level: 85 },
    { name: "ArgoCD", level: 90 },
  ],
  monitoring: [
    { name: "Grafana", level: 90 },
    { name: "Prometheus", level: 90 },
    { name: "ELK Stack", level: 85 },
    { name: "Datadog", level: 85 },
  ],
};

export const experience = [
  {
    id: 1,
    role: "Senior Full Stack & Mobile Developer",
    company: "TechCorp Global",
    duration: "2022 - Present",
    description: "Leading full-stack web and mobile development, cloud infrastructure, and DevOps initiatives for enterprise-scale applications.",
    responsibilities: [
      "Architected and deployed microservices infrastructure on AWS EKS serving 10M+ users",
      "Developed cross-platform mobile applications using React Native for iOS and Android",
      "Built responsive web applications with Next.js and React serving millions of users",
      "Reduced deployment time by 75% through CI/CD pipeline optimization",
      "Implemented GitOps workflows using ArgoCD and Flux",
      "Built Infrastructure as Code using Terraform for multi-region deployments",
    ],
    technologies: ["React Native", "React", "Next.js", "TypeScript", "Kubernetes", "AWS", "Terraform", "ArgoCD", "GitHub Actions"],
    achievements: [
      "Launched 3 mobile apps with 500K+ combined downloads",
      "Reduced infrastructure costs by 40% through resource optimization",
      "Achieved 99.99% uptime SLA",
      "Decreased incident response time by 60%",
    ],
  },
  {
    id: 2,
    role: "Full Stack Engineer & DevOps Lead",
    company: "CloudScale Solutions",
    duration: "2020 - 2022",
    description: "Built and scaled cloud-native applications with focus on automation and reliability.",
    responsibilities: [
      "Developed full-stack applications using React, Node.js, and PostgreSQL",
      "Designed and implemented CI/CD pipelines reducing deployment time by 80%",
      "Managed Kubernetes clusters with 200+ microservices",
      "Led migration from monolith to microservices architecture",
    ],
    technologies: ["React", "Node.js", "Docker", "Kubernetes", "Jenkins", "AWS"],
    achievements: [
      "Successfully migrated 50+ services to Kubernetes",
      "Improved application performance by 3x",
      "Reduced cloud costs by $50K/month",
    ],
  },
  {
    id: 3,
    role: "Software Engineer",
    company: "StartupTech Inc",
    duration: "2018 - 2020",
    description: "Full-stack development and early-stage infrastructure setup.",
    responsibilities: [
      "Built customer-facing web applications using React and Node.js",
      "Set up initial DevOps practices and CI/CD pipelines",
      "Implemented automated testing and deployment workflows",
      "Collaborated with product team on feature development",
    ],
    technologies: ["React", "Node.js", "MongoDB", "Docker", "AWS", "CircleCI"],
    achievements: [
      "Delivered 20+ features from concept to production",
      "Established DevOps best practices",
      "Reduced bug count by 50% through automated testing",
    ],
  },
];

export const projects = [
  {
    id: "kubernetes-platform",
    title: "Enterprise Kubernetes Platform",
    description: "Production-grade Kubernetes platform serving 100+ microservices with automated scaling, monitoring, and disaster recovery.",
    image: "/placeholder.svg",
    technologies: ["Kubernetes", "Helm", "ArgoCD", "Prometheus", "Grafana", "Terraform"],
    github: "https://github.com",
    demo: "https://demo.example.com",
    featured: true,
  },
  {
    id: "cicd-pipeline",
    title: "Multi-Cloud CI/CD Pipeline",
    description: "Unified CI/CD pipeline supporting AWS, GCP, and Azure with automated security scanning and compliance checks.",
    image: "/placeholder.svg",
    technologies: ["GitHub Actions", "Terraform", "Docker", "Trivy", "SonarQube"],
    github: "https://github.com",
    demo: "https://demo.example.com",
    featured: true,
  },
  {
    id: "monitoring-stack",
    title: "Observability Stack",
    description: "Complete monitoring solution with metrics, logs, and traces using Prometheus, Grafana, and Loki.",
    image: "/placeholder.svg",
    technologies: ["Prometheus", "Grafana", "Loki", "Tempo", "Kubernetes"],
    github: "https://github.com",
    demo: "https://demo.example.com",
    featured: true,
  },
  {
    id: "infrastructure-automation",
    title: "Infrastructure Automation Platform",
    description: "Self-service platform for provisioning cloud resources with cost tracking and governance policies.",
    image: "/placeholder.svg",
    technologies: ["Terraform", "AWS", "Python", "React", "PostgreSQL"],
    github: "https://github.com",
    demo: "https://demo.example.com",
    featured: false,
  },
  {
    id: "fitness-tracker-app",
    title: "FitTrack - Fitness & Wellness App",
    description: "Cross-platform mobile app for fitness tracking with workout plans, nutrition logging, and social features. Built with React Native and Firebase.",
    image: "/placeholder.svg",
    technologies: ["React Native", "Expo", "TypeScript", "Firebase", "Redux Toolkit", "React Navigation"],
    github: "https://github.com",
    demo: "https://apps.apple.com",
    featured: true,
  },
  {
    id: "ecommerce-mobile-app",
    title: "ShopEase - E-commerce Mobile App",
    description: "Feature-rich e-commerce mobile application with real-time inventory, secure payments, and personalized recommendations.",
    image: "/placeholder.svg",
    technologies: ["React Native", "TypeScript", "Stripe", "Firebase", "Redux", "Push Notifications"],
    github: "https://github.com",
    demo: "https://play.google.com",
    featured: true,
  },
];

export const caseStudies = [
  {
    id: "aws-eks-migration",
    title: "AWS EKS Migration & Optimization",
    description: "Migrated 50+ microservices from EC2 to EKS, reducing costs by 40% and improving reliability.",
    image: "/placeholder.svg",
    tools: ["AWS EKS", "Terraform", "Helm", "ArgoCD", "Kubernetes"],
    problem: "Legacy EC2-based infrastructure was expensive, hard to manage, and lacked proper scaling.",
    approach: [
      "Assessed current architecture and identified migration candidates",
      "Built EKS clusters with proper networking and security",
      "Implemented GitOps workflows using ArgoCD",
      "Migrated services incrementally with zero downtime",
      "Set up comprehensive monitoring and alerting",
    ],
    outcome: "40% cost reduction, 99.99% uptime, deployment time reduced from hours to minutes.",
    metrics: {
      costReduction: "40%",
      uptime: "99.99%",
      deploymentTime: "95% faster",
      incidents: "70% fewer",
    },
  },
  {
    id: "cicd-optimization",
    title: "CI/CD Pipeline Optimization",
    description: "Redesigned CI/CD pipelines reducing build times from 45 minutes to 8 minutes.",
    image: "/placeholder.svg",
    tools: ["GitHub Actions", "Docker", "BuildKit", "Kubernetes", "ArgoCD"],
    problem: "Slow CI/CD pipelines causing delays and developer frustration.",
    approach: [
      "Analyzed bottlenecks in existing pipelines",
      "Implemented build caching and layer optimization",
      "Parallelized test execution",
      "Optimized Docker builds with multi-stage builds",
      "Set up automated deployment verification",
    ],
    outcome: "Build times reduced by 82%, deployment frequency increased 5x.",
    metrics: {
      buildTime: "82% faster",
      deploymentFrequency: "5x increase",
      developerSatisfaction: "95%",
      failureRate: "60% reduction",
    },
  },
  {
    id: "kubernetes-autoscaling",
    title: "Kubernetes Auto-scaling Implementation",
    description: "Implemented HPA and VPA for cost-efficient scaling handling 10x traffic spikes.",
    image: "/placeholder.svg",
    tools: ["Kubernetes", "HPA", "VPA", "Prometheus", "Grafana"],
    problem: "Manual scaling couldn't handle traffic spikes, leading to downtime and over-provisioning.",
    approach: [
      "Analyzed traffic patterns and resource utilization",
      "Implemented Horizontal Pod Autoscaler (HPA)",
      "Configured Vertical Pod Autoscaler (VPA)",
      "Set up custom metrics with Prometheus",
      "Fine-tuned scaling parameters",
    ],
    outcome: "Handled 10x traffic spikes automatically, reduced costs by 35%.",
    metrics: {
      costReduction: "35%",
      autoScaling: "100% automated",
      responseTime: "50% improvement",
      downtime: "Zero during spikes",
    },
  },
];

export const blogPosts = [
  {
    id: "kubernetes-best-practices",
    title: "Kubernetes Production Best Practices in 2024",
    excerpt: "Essential practices for running Kubernetes in production, from security to cost optimization.",
    date: "2024-03-15",
    category: "DevOps & Cloud",
    readTime: "8 min read",
    image: "/placeholder.svg",
  },
  {
    id: "cicd-pipeline-optimization",
    title: "Optimizing CI/CD Pipelines: From 45 to 8 Minutes",
    excerpt: "How we reduced build times by 82% using caching, parallelization, and smart optimization.",
    date: "2024-02-20",
    category: "DevOps & Cloud",
    readTime: "10 min read",
    image: "/placeholder.svg",
  },
  {
    id: "microservices-architecture",
    title: "Building Scalable Microservices: Lessons from Production",
    excerpt: "Real-world insights from managing 100+ microservices in production.",
    date: "2024-01-10",
    category: "Software Engineering",
    readTime: "12 min read",
    image: "/placeholder.svg",
  },
];
